include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/**
  errors:
    missing_required_param: error
    missing_return: error

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - use_super_parameters
    - prefer_single_quotes
    - require_trailing_commas
